AWSTemplateFormatVersion: "2010-09-09"
Description: iam role for github actions

Parameters:
  TrustedAccountId:
    Type: String
    Description: AWS Account ID that is allowed to assume this role

Resources:

  GithubActionsRoleApp:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-app"
      AssumeRolePolicyDocument:
        Statement:
          # for GithubActions
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - repo:blue21jp/aws-resources-visualiser:*
          # for act
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub "arn:aws:iam::${TrustedAccountId}:root"
      Policies:
        - PolicyName: gha-allow
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # アカウントID確認権限
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
              # ECR操作権限
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                Resource: '*'
              # S3操作権限
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::awsresourcevisualizer-source-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::awsresourcevisualizer-source-${AWS::AccountId}/*'

  GithubActionsRoleBatch:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-batch"
      AssumeRolePolicyDocument:
        Statement:
          # for GithubActions
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - repo:blue21jp/aws-resources-visualiser:*
          # for act
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub "arn:aws:iam::${TrustedAccountId}:root"
      Policies:
        - PolicyName: gha-allow
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # アカウントID確認権限
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
              # ECS操作権限
              - Effect: Allow
                Action:
                  - ecs:ListTasks
                  - ecs:ExecuteCommand
                  - ecs:DescribeTasks
                Resource: '*'

  GithubActionsRoleRain:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-rain"
      AssumeRolePolicyDocument:
        Statement:
          # for GithubActions
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - repo:blue21jp/aws-resources-visualiser:*
          # for act
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub "arn:aws:iam::${TrustedAccountId}:root"
      Policies:
        - PolicyName: gha-allow
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # アカウントID確認権限
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
              # CloudFormation操作権限
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:DescribeStackResource
                  - cloudformation:GetTemplate
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ListChangeSets
                Resource: '*'
              # IAM操作権限
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:PassRole
                  - iam:TagRole
                  - iam:UntagRole
                Resource: '*'
              # EC2操作権限
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:DescribeVpcs
                  - ec2:DescribePrefixLists
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DescribeTags
                Resource: '*'
              # ECR操作権限
              - Effect: Allow
                Action:
                  - ecr:DescribeImages
                Resource: '*'
              # ECS操作権限
              - Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - ecs:DeleteCluster
                  - ecs:DescribeClusters
                  - ecs:CreateService
                  - ecs:DeleteService
                  - ecs:DescribeServices
                  - ecs:UpdateService
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition
                  - ecs:DescribeTaskDefinition
                  - ecs:ListTaskDefinitions
                  - ecs:TagResource
                  - ecs:UntagResource
                  - ecs:ListTagsForResource
                Resource: '*'
              # CloudWatch Logs操作権限
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:DescribeLogGroups
                  - logs:PutRetentionPolicy
                  - logs:DeleteRetentionPolicy
                  - logs:TagLogGroup
                  - logs:UntagLogGroup
                Resource: '*'
              # SSM操作権限
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                  - ssm:GetParameter
                Resource: '*'
              # S3操作権限（rain用）
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketVersioning
                  - s3:PutBucketVersioning
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                Resource:
                  - !Sub 'arn:aws:s3:::rain-artifacts-${AWS::AccountId}-${AWS::Region}'
                  - !Sub 'arn:aws:s3:::rain-artifacts-${AWS::AccountId}-${AWS::Region}/*'

Outputs:
  GithubActionsRoleAppArn:
    Value: !GetAtt GithubActionsRoleApp.Arn

  GithubActionsRoleBatchArn:
    Value: !GetAtt GithubActionsRoleBatch.Arn

  GithubActionsRoleRainArn:
    Value: !GetAtt GithubActionsRoleRain.Arn
